myfile=open("book.txt","w")
myfile.write("abcdefghijkl")
myfile.write("mnopqrst")
myfile.write("uvwxyz")
myfile.close()
myfile1=open("book.txt")
myfile2=open("bookback.txt","w")
str1=" "
while str1!="":
    str1=myfile1.readline()
    myfile2.write(str1)
myfile1.close()
myfile2.close()
myfile3=open("book.txt")
myfile4=open("bookback.txt")
a=myfile3.read()
b=myfile4.read()
print(a)
print(b)