#10, TO PRINT DICTIONARY WITH MOTNH AND NO OF DAYS IN THAT MONTH
#auhor: ASWIN P
#date:27/02/2022
print("TO PRINT DICTIONARY WITH MOTNH AND NO OF DAYS IN THAT MONTH")
print()
Dyear={"JANUARY":31,"FEBRUARY":28,"MARCH":31,"APRIL":30,"MAY":31,"JUNE":30,"JULY":31,"AUGUST":31,"SEPTEMBER":30,"OCTOBER":31,"NOVEMBOR":30,"DECEMBER":31}
print()
s=input("ENTER THE MONTH TO SEARCH: ")
S=s.upper()
if S in Dyear:
    D=Dyear.get(S)
    print("no. OF DAYS IN ",s,"=",D)
print()
print("******THANKS FOR USING THIS PROGRAM******")